#!/bin/bash
# 
# To invoke remotely: bash -c "$(curl -fsSkL example.org/path/to/this/script)"
#
%init check_macosx check_xquartz check_noinstalldir create_installdir ask tell

trap tell EXIT
tell
tell "Welcome to the $desc installer."
tell "For more information, please see $url"
tell

check_macosx

rsync "$rsyncsrc/$installdir/" >/dev/null || {
  err=$?
  tell "Cannot access software repository."
  (($err==23)) && tell "Repository seems not to exist; perhaps this platform is not supported?"
  exit $err
}

check_xquartz
check_noinstalldir

[[ $(groups) =~ (^| )admin( |$) ]] || { tell "You must be an administrator to install."; exit 1; }

tell "This script will create and install into $installdir"
ask "Proceed?" || { tell "Exiting with no filesystem changes."; exit 1; }
create_installdir
rsync -aR "$rsyncsrc/$installdir/./${upgrade#$installdir}" "$installdir" || {
  tell "Initialization failed; aborting."; exit 1; }

tell
tell "Initialization complete."
tell "Now doing first upgrade using $upgrade"
"$upgrade" --checkpath
